# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Aula1_15Feb2016/Nexys4_Master.xdc

# Block Designs: bd/MP3_Design/MP3_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design || ORIG_REF_NAME==MP3_Design}]

# IP: bd/MP3_Design/ip/MP3_Design_microblaze_0_0/MP3_Design_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_microblaze_0_0 || ORIG_REF_NAME==MP3_Design_microblaze_0_0}]

# IP: bd/MP3_Design/ip/MP3_Design_dlmb_v10_0/MP3_Design_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_dlmb_v10_0 || ORIG_REF_NAME==MP3_Design_dlmb_v10_0}]

# IP: bd/MP3_Design/ip/MP3_Design_ilmb_v10_0/MP3_Design_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_ilmb_v10_0 || ORIG_REF_NAME==MP3_Design_ilmb_v10_0}]

# IP: bd/MP3_Design/ip/MP3_Design_dlmb_bram_if_cntlr_0/MP3_Design_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MP3_Design_dlmb_bram_if_cntlr_0}]

# IP: bd/MP3_Design/ip/MP3_Design_ilmb_bram_if_cntlr_0/MP3_Design_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MP3_Design_ilmb_bram_if_cntlr_0}]

# IP: bd/MP3_Design/ip/MP3_Design_lmb_bram_0/MP3_Design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_lmb_bram_0 || ORIG_REF_NAME==MP3_Design_lmb_bram_0}]

# IP: bd/MP3_Design/ip/MP3_Design_microblaze_0_axi_periph_0/MP3_Design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MP3_Design_microblaze_0_axi_periph_0}]

# IP: bd/MP3_Design/ip/MP3_Design_mdm_1_0/MP3_Design_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_mdm_1_0 || ORIG_REF_NAME==MP3_Design_mdm_1_0}]

# IP: bd/MP3_Design/ip/MP3_Design_clk_wiz_1_0/MP3_Design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_clk_wiz_1_0 || ORIG_REF_NAME==MP3_Design_clk_wiz_1_0}]

# IP: bd/MP3_Design/ip/MP3_Design_rst_clk_wiz_1_100M_0/MP3_Design_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MP3_Design_rst_clk_wiz_1_100M_0}]

# IP: bd/MP3_Design/ip/MP3_Design_axi_gpio_0_0/MP3_Design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_axi_gpio_0_0 || ORIG_REF_NAME==MP3_Design_axi_gpio_0_0}]

# IP: bd/MP3_Design/ip/MP3_Design_DC32_0_0/MP3_Design_DC32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_DC32_0_0 || ORIG_REF_NAME==MP3_Design_DC32_0_0}]

# IP: bd/MP3_Design/ip/MP3_Design_BinToBCD16_0_0/MP3_Design_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_BinToBCD16_0_0 || ORIG_REF_NAME==MP3_Design_BinToBCD16_0_0}]

# IP: bd/MP3_Design/ip/MP3_Design_xlslice_0_0/MP3_Design_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_xlslice_0_0 || ORIG_REF_NAME==MP3_Design_xlslice_0_0}]

# IP: bd/MP3_Design/ip/MP3_Design_xlslice_1_0/MP3_Design_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_xlslice_1_0 || ORIG_REF_NAME==MP3_Design_xlslice_1_0}]

# IP: bd/MP3_Design/ip/MP3_Design_xlconcat_0_0/MP3_Design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_xlconcat_0_0 || ORIG_REF_NAME==MP3_Design_xlconcat_0_0}]

# IP: bd/MP3_Design/ip/MP3_Design_xlconstant_0_0/MP3_Design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_xlconstant_0_0 || ORIG_REF_NAME==MP3_Design_xlconstant_0_0}]

# IP: bd/MP3_Design/ip/MP3_Design_xlconstant_1_0/MP3_Design_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_xlconstant_1_0 || ORIG_REF_NAME==MP3_Design_xlconstant_1_0}]

# IP: bd/MP3_Design/ip/MP3_Design_xbar_0/MP3_Design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_xbar_0 || ORIG_REF_NAME==MP3_Design_xbar_0}]

# IP: bd/MP3_Design/ip/MP3_Design_axi_gpio_1_0/MP3_Design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_axi_gpio_1_0 || ORIG_REF_NAME==MP3_Design_axi_gpio_1_0}]

# IP: bd/MP3_Design/ip/MP3_Design_auto_pc_0/MP3_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_auto_pc_0 || ORIG_REF_NAME==MP3_Design_auto_pc_0}]

# IP: bd/MP3_Design/ip/MP3_Design_auto_pc_1/MP3_Design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP3_Design_auto_pc_1 || ORIG_REF_NAME==MP3_Design_auto_pc_1}]

# XDC: bd/MP3_Design/ip/MP3_Design_microblaze_0_0/MP3_Design_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_microblaze_0_0 || ORIG_REF_NAME==MP3_Design_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_microblaze_0_0/MP3_Design_microblaze_0_0_ooc_debug.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_microblaze_0_0/MP3_Design_microblaze_0_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_dlmb_v10_0/MP3_Design_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_dlmb_v10_0 || ORIG_REF_NAME==MP3_Design_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_dlmb_v10_0/MP3_Design_dlmb_v10_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_ilmb_v10_0/MP3_Design_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_ilmb_v10_0 || ORIG_REF_NAME==MP3_Design_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_ilmb_v10_0/MP3_Design_ilmb_v10_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_dlmb_bram_if_cntlr_0/MP3_Design_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_ilmb_bram_if_cntlr_0/MP3_Design_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_lmb_bram_0/MP3_Design_lmb_bram_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_mdm_1_0/MP3_Design_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_mdm_1_0 || ORIG_REF_NAME==MP3_Design_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_mdm_1_0/MP3_Design_mdm_1_0_ooc_trace.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_mdm_1_0/MP3_Design_mdm_1_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_clk_wiz_1_0/MP3_Design_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_clk_wiz_1_0 || ORIG_REF_NAME==MP3_Design_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/MP3_Design/ip/MP3_Design_clk_wiz_1_0/MP3_Design_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_clk_wiz_1_0 || ORIG_REF_NAME==MP3_Design_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/MP3_Design/ip/MP3_Design_clk_wiz_1_0/MP3_Design_clk_wiz_1_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_rst_clk_wiz_1_100M_0/MP3_Design_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MP3_Design_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_rst_clk_wiz_1_100M_0/MP3_Design_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MP3_Design_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_rst_clk_wiz_1_100M_0/MP3_Design_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_axi_gpio_0_0/MP3_Design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_axi_gpio_0_0 || ORIG_REF_NAME==MP3_Design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_axi_gpio_0_0/MP3_Design_axi_gpio_0_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_axi_gpio_0_0/MP3_Design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_axi_gpio_0_0 || ORIG_REF_NAME==MP3_Design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_xbar_0/MP3_Design_xbar_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_axi_gpio_1_0/MP3_Design_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_axi_gpio_1_0 || ORIG_REF_NAME==MP3_Design_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_axi_gpio_1_0/MP3_Design_axi_gpio_1_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_axi_gpio_1_0/MP3_Design_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MP3_Design_axi_gpio_1_0 || ORIG_REF_NAME==MP3_Design_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/MP3_Design/ip/MP3_Design_auto_pc_0/MP3_Design_auto_pc_0_ooc.xdc

# XDC: bd/MP3_Design/ip/MP3_Design_auto_pc_1/MP3_Design_auto_pc_1_ooc.xdc

# XDC: bd/MP3_Design/MP3_Design_ooc.xdc
