# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir k:/cr_microblase/mp3/mp3.tmp/dc32_v1_0_project/DC32_v1_0_project.cache/wt [current_project]
set_property parent.project_path k:/cr_microblase/mp3/mp3.tmp/dc32_v1_0_project/DC32_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths k:/CR_MicroBlase/REPOSITORY [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library work {
  k:/cr_microblase/repository/displaycontrol32inputs/displaycontrol32inputs.srcs/sources_1/imports/new/segment_decoder.vhd
  k:/cr_microblase/repository/displaycontrol32inputs/displaycontrol32inputs.srcs/sources_1/imports/new/disp.vhd
}
synth_design -top DC32 -part xc7a100tcsg324-1
write_checkpoint -noxdef DC32.dcp
catch { report_utilization -file DC32_utilization_synth.rpt -pb DC32_utilization_synth.pb }
