# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Aula1_15Feb2016/Nexys4_Master.xdc

# Block Designs: bd/MB_swled/MB_swled.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled || ORIG_REF_NAME==MB_swled}]

# IP: bd/MB_swled/ip/MB_swled_microblaze_0_0/MB_swled_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_microblaze_0_0 || ORIG_REF_NAME==MB_swled_microblaze_0_0}]

# IP: bd/MB_swled/ip/MB_swled_dlmb_v10_0/MB_swled_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_dlmb_v10_0 || ORIG_REF_NAME==MB_swled_dlmb_v10_0}]

# IP: bd/MB_swled/ip/MB_swled_ilmb_v10_0/MB_swled_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_ilmb_v10_0 || ORIG_REF_NAME==MB_swled_ilmb_v10_0}]

# IP: bd/MB_swled/ip/MB_swled_dlmb_bram_if_cntlr_0/MB_swled_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_swled_dlmb_bram_if_cntlr_0}]

# IP: bd/MB_swled/ip/MB_swled_ilmb_bram_if_cntlr_0/MB_swled_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_swled_ilmb_bram_if_cntlr_0}]

# IP: bd/MB_swled/ip/MB_swled_lmb_bram_0/MB_swled_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_lmb_bram_0 || ORIG_REF_NAME==MB_swled_lmb_bram_0}]

# IP: bd/MB_swled/ip/MB_swled_microblaze_0_axi_periph_0/MB_swled_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_swled_microblaze_0_axi_periph_0}]

# IP: bd/MB_swled/ip/MB_swled_mdm_1_0/MB_swled_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_mdm_1_0 || ORIG_REF_NAME==MB_swled_mdm_1_0}]

# IP: bd/MB_swled/ip/MB_swled_clk_wiz_1_0/MB_swled_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_clk_wiz_1_0 || ORIG_REF_NAME==MB_swled_clk_wiz_1_0}]

# IP: bd/MB_swled/ip/MB_swled_rst_clk_wiz_1_100M_0/MB_swled_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_swled_rst_clk_wiz_1_100M_0}]

# IP: bd/MB_swled/ip/MB_swled_axi_gpio_0_0/MB_swled_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_axi_gpio_0_0 || ORIG_REF_NAME==MB_swled_axi_gpio_0_0}]

# IP: bd/MB_swled/ip/MB_swled_xbar_0/MB_swled_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_xbar_0 || ORIG_REF_NAME==MB_swled_xbar_0}]

# IP: bd/MB_swled/ip/MB_swled_auto_pc_0/MB_swled_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_auto_pc_0 || ORIG_REF_NAME==MB_swled_auto_pc_0}]

# IP: bd/MB_swled/ip/MB_swled_auto_pc_1/MB_swled_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_auto_pc_1 || ORIG_REF_NAME==MB_swled_auto_pc_1}]

# XDC: bd/MB_swled/ip/MB_swled_microblaze_0_0/MB_swled_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_microblaze_0_0 || ORIG_REF_NAME==MB_swled_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_swled/ip/MB_swled_microblaze_0_0/MB_swled_microblaze_0_0_ooc_debug.xdc

# XDC: bd/MB_swled/ip/MB_swled_microblaze_0_0/MB_swled_microblaze_0_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_dlmb_v10_0/MB_swled_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_dlmb_v10_0 || ORIG_REF_NAME==MB_swled_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_swled/ip/MB_swled_dlmb_v10_0/MB_swled_dlmb_v10_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_ilmb_v10_0/MB_swled_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_ilmb_v10_0 || ORIG_REF_NAME==MB_swled_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_swled/ip/MB_swled_ilmb_v10_0/MB_swled_ilmb_v10_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_dlmb_bram_if_cntlr_0/MB_swled_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_ilmb_bram_if_cntlr_0/MB_swled_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_lmb_bram_0/MB_swled_lmb_bram_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_mdm_1_0/MB_swled_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_mdm_1_0 || ORIG_REF_NAME==MB_swled_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_swled/ip/MB_swled_mdm_1_0/MB_swled_mdm_1_0_ooc_trace.xdc

# XDC: bd/MB_swled/ip/MB_swled_mdm_1_0/MB_swled_mdm_1_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_clk_wiz_1_0/MB_swled_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_clk_wiz_1_0 || ORIG_REF_NAME==MB_swled_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/MB_swled/ip/MB_swled_clk_wiz_1_0/MB_swled_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_clk_wiz_1_0 || ORIG_REF_NAME==MB_swled_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/MB_swled/ip/MB_swled_clk_wiz_1_0/MB_swled_clk_wiz_1_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_rst_clk_wiz_1_100M_0/MB_swled_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_swled_rst_clk_wiz_1_100M_0}]

# XDC: bd/MB_swled/ip/MB_swled_rst_clk_wiz_1_100M_0/MB_swled_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_swled_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_swled_rst_clk_wiz_1_100M_0}]

# XDC: bd/MB_swled/ip/MB_swled_rst_clk_wiz_1_100M_0/MB_swled_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_axi_gpio_0_0/MB_swled_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_axi_gpio_0_0 || ORIG_REF_NAME==MB_swled_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_swled/ip/MB_swled_axi_gpio_0_0/MB_swled_axi_gpio_0_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_axi_gpio_0_0/MB_swled_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_swled_axi_gpio_0_0 || ORIG_REF_NAME==MB_swled_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_swled/ip/MB_swled_xbar_0/MB_swled_xbar_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_auto_pc_0/MB_swled_auto_pc_0_ooc.xdc

# XDC: bd/MB_swled/ip/MB_swled_auto_pc_1/MB_swled_auto_pc_1_ooc.xdc

# XDC: bd/MB_swled/MB_swled_ooc.xdc
