# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.cache/wt [current_project]
set_property parent.project_path /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.srcs/sources_1/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.srcs/constrs_1/imports/xdc/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /media/psf/Home/Development/ect_ua/reconfigurable-computation/Aula08/Projects2016/UserDefinedRepository/HammingWeightV3/hammingweight_v3/hammingweight_v3.srcs/constrs_1/imports/xdc/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
