# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/Nexys4_Master.xdc

# Block Designs: bd/exam_design/exam_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design || ORIG_REF_NAME==exam_design}]

# IP: bd/exam_design/ip/exam_design_blk_mem_gen_0_0/exam_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_blk_mem_gen_0_0 || ORIG_REF_NAME==exam_design_blk_mem_gen_0_0}]

# IP: bd/exam_design/ip/exam_design_blk_mem_gen_1_0/exam_design_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_blk_mem_gen_1_0 || ORIG_REF_NAME==exam_design_blk_mem_gen_1_0}]

# IP: bd/exam_design/ip/exam_design_ROM_Reader1_0_0/exam_design_ROM_Reader1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_ROM_Reader1_0_0 || ORIG_REF_NAME==exam_design_ROM_Reader1_0_0}]

# IP: bd/exam_design/ip/exam_design_ROM_Reader1_0_1/exam_design_ROM_Reader1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_ROM_Reader1_0_1 || ORIG_REF_NAME==exam_design_ROM_Reader1_0_1}]

# IP: bd/exam_design/ip/exam_design_iterative_sorter_0_0/exam_design_iterative_sorter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_iterative_sorter_0_0 || ORIG_REF_NAME==exam_design_iterative_sorter_0_0}]

# IP: bd/exam_design/ip/exam_design_iterative_sorter_0_1/exam_design_iterative_sorter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_iterative_sorter_0_1 || ORIG_REF_NAME==exam_design_iterative_sorter_0_1}]

# IP: bd/exam_design/ip/exam_design_mux2p_0_0/exam_design_mux2p_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_mux2p_0_0 || ORIG_REF_NAME==exam_design_mux2p_0_0}]

# IP: bd/exam_design/ip/exam_design_xlslice_0_0/exam_design_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_xlslice_0_0 || ORIG_REF_NAME==exam_design_xlslice_0_0}]

# IP: bd/exam_design/ip/exam_design_xlslice_0_1/exam_design_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_xlslice_0_1 || ORIG_REF_NAME==exam_design_xlslice_0_1}]

# IP: bd/exam_design/ip/exam_design_smart_mux_0_0/exam_design_smart_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_smart_mux_0_0 || ORIG_REF_NAME==exam_design_smart_mux_0_0}]

# IP: bd/exam_design/ip/exam_design_EightDisplayControl_0_0/exam_design_EightDisplayControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_design_EightDisplayControl_0_0 || ORIG_REF_NAME==exam_design_EightDisplayControl_0_0}]

# XDC: bd/exam_design/ip/exam_design_blk_mem_gen_0_0/exam_design_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/exam_design/ip/exam_design_blk_mem_gen_1_0/exam_design_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/exam_design/ip/exam_design_smart_mux_0_0/constrs_1/imports/xdc/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==exam_design_smart_mux_0_0 || ORIG_REF_NAME==exam_design_smart_mux_0_0}] {/U0 }]/U0 ]]

# XDC: bd/exam_design/exam_design_ooc.xdc
