# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.cache/wt} [current_project]
set_property parent.project_path {/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /media/psf/Home/Development/ect_ua/UserRepository/Repository [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /media/psf/Home/Development/ect_ua/UserRepository/Memoria/4words4bits_1.coe
add_files /media/psf/Home/Development/ect_ua/UserRepository/Memoria/4words4bits_2.coe
add_files {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/sources_1/bd/exam_design/exam_design.bd}}
set_property used_in_implementation false [get_files -all {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/sources_1/bd/exam_design/ip/exam_design_blk_mem_gen_0_0/exam_design_blk_mem_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/sources_1/bd/exam_design/ip/exam_design_blk_mem_gen_1_0/exam_design_blk_mem_gen_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/sources_1/bd/exam_design/ip/exam_design_smart_mux_0_0/constrs_1/imports/xdc/Nexys4_Master.xdc}}]
set_property used_in_implementation false [get_files -all {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/sources_1/bd/exam_design/exam_design_ooc.xdc}}]
set_property is_locked true [get_files {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/sources_1/bd/exam_design/exam_design.bd}}]

read_vhdl -library xil_defaultlib {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/sources_1/bd/exam_design/hdl/exam_design_wrapper.vhd}}
read_xdc {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/constrs_1/imports/xdc/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P1 13 Abril 2015/project/project.srcs/constrs_1/imports/xdc/Nexys4_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top exam_design_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef exam_design_wrapper.dcp
catch { report_utilization -file exam_design_wrapper_utilization_synth.rpt -pb exam_design_wrapper_utilization_synth.pb }
