# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir I:/SDR_P/8/UserDefinedRepository/Unroll_ROM_last/Unroll_ROM_last.cache/wt [current_project]
set_property parent.project_path I:/SDR_P/8/UserDefinedRepository/Unroll_ROM_last/Unroll_ROM_last.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths I:/SDR_P/8/UserDefinedRepository [current_project]
read_vhdl -library work I:/SDR_P/8/UserDefinedRepository/Unroll_ROM_last/Unroll_ROM_last.srcs/sources_1/imports/new/ROM_reader_top.vhd
catch { write_hwdef -file Unroll_ROM_last.hwdef }
synth_design -top Unroll_ROM_last -part xc7a100tcsg324-1
write_checkpoint -noxdef Unroll_ROM_last.dcp
catch { report_utilization -file Unroll_ROM_last_utilization_synth.rpt -pb Unroll_ROM_last_utilization_synth.pb }
