# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula8_11april2016/Projects2016/REPOSITORY/DisplayControl32inputs/DisplayControl32inputs.cache/wt [current_project]
set_property parent.project_path K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula8_11april2016/Projects2016/REPOSITORY/DisplayControl32inputs/DisplayControl32inputs.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths k:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula8_11april2016/Projects2016/REPOSITORY/DisplayControl32inputs/DisplayControl32inputs.srcs/sources_1/imports/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library work {
  K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula8_11april2016/Projects2016/REPOSITORY/DisplayControl32inputs/DisplayControl32inputs.srcs/sources_1/imports/new/segment_decoder.vhd
  K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula8_11april2016/Projects2016/REPOSITORY/DisplayControl32inputs/DisplayControl32inputs.srcs/sources_1/imports/new/disp.vhd
}
synth_design -top DC32 -part xc7a100tcsg324-1
write_checkpoint -noxdef DC32.dcp
catch { report_utilization -file DC32_utilization_synth.rpt -pb DC32_utilization_synth.pb }
