# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/psf/Home/Development/ect_ua/UserRepository/Repository/resetCircuit/resetCircuit.cache/wt [current_project]
set_property parent.project_path /media/psf/Home/Development/ect_ua/UserRepository/Repository/resetCircuit/resetCircuit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /media/psf/Home/Development/ect_ua/UserRepository/Repository/resetCircuit/resetCircuit.srcs/sources_1/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib /media/psf/Home/Development/ect_ua/UserRepository/Repository/resetCircuit/resetCircuit.srcs/sources_1/new/resetCircuit.vhd
synth_design -top resetCircuit -part xc7a100tcsg324-1
write_checkpoint -noxdef resetCircuit.dcp
catch { report_utilization -file resetCircuit_utilization_synth.rpt -pb resetCircuit_utilization_synth.pb }
