# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/psf/Home/Development/ect_ua/UserRepository/Repository/circuito_p/circuito_p.cache/wt [current_project]
set_property parent.project_path /media/psf/Home/Development/ect_ua/UserRepository/Repository/circuito_p/circuito_p.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /media/psf/Home/Development/ect_ua/UserRepository/Repository/circuito_p/circuito_p.srcs/sources_1/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib /media/psf/Home/Development/ect_ua/UserRepository/Repository/circuito_p/circuito_p.srcs/sources_1/new/circuit_p.vhd
synth_design -top circuit -part xc7a100tcsg324-1
write_checkpoint -noxdef circuit.dcp
catch { report_utilization -file circuit_utilization_synth.rpt -pb circuit_utilization_synth.pb }
