# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/Nexys4_Master.xdc

# Block Designs: bd/exam/exam.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam || ORIG_REF_NAME==exam}]

# IP: bd/exam/ip/exam_blk_mem_gen_0_0/exam_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_blk_mem_gen_0_0 || ORIG_REF_NAME==exam_blk_mem_gen_0_0}]

# IP: bd/exam/ip/exam_ROM_Reader1_0_0/exam_ROM_Reader1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_ROM_Reader1_0_0 || ORIG_REF_NAME==exam_ROM_Reader1_0_0}]

# IP: bd/exam/ip/exam_DC32_0_0/exam_DC32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_DC32_0_0 || ORIG_REF_NAME==exam_DC32_0_0}]

# IP: bd/exam/ip/exam_MaxNetworkExam_0_2/exam_MaxNetworkExam_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_MaxNetworkExam_0_2 || ORIG_REF_NAME==exam_MaxNetworkExam_0_2}]

# IP: bd/exam/ip/exam_xlslice_0_0/exam_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlslice_0_0 || ORIG_REF_NAME==exam_xlslice_0_0}]

# IP: bd/exam/ip/exam_resetCircuit_0_0/exam_resetCircuit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_resetCircuit_0_0 || ORIG_REF_NAME==exam_resetCircuit_0_0}]

# IP: bd/exam/ip/exam_xlconcat_0_0/exam_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconcat_0_0 || ORIG_REF_NAME==exam_xlconcat_0_0}]

# IP: bd/exam/ip/exam_xlconstant_0_0/exam_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconstant_0_0 || ORIG_REF_NAME==exam_xlconstant_0_0}]

# XDC: bd/exam/ip/exam_blk_mem_gen_0_0/exam_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/exam/exam_ooc.xdc
