# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/Nexys4_Master.xdc

# Block Designs: bd/project/project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project || ORIG_REF_NAME==project}]

# IP: bd/project/ip/project_blk_mem_gen_0_0/project_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_blk_mem_gen_0_0 || ORIG_REF_NAME==project_blk_mem_gen_0_0}]

# IP: bd/project/ip/project_EightDisplayControl_0_0/project_EightDisplayControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_EightDisplayControl_0_0 || ORIG_REF_NAME==project_EightDisplayControl_0_0}]

# IP: bd/project/ip/project_xlslice_0_0/project_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_xlslice_0_0 || ORIG_REF_NAME==project_xlslice_0_0}]

# IP: bd/project/ip/project_xlslice_0_1/project_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_xlslice_0_1 || ORIG_REF_NAME==project_xlslice_0_1}]

# IP: bd/project/ip/project_hw_0_0/project_hw_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_hw_0_0 || ORIG_REF_NAME==project_hw_0_0}]

# IP: bd/project/ip/project_circuitp_0_0/project_circuitp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_circuitp_0_0 || ORIG_REF_NAME==project_circuitp_0_0}]

# XDC: bd/project/ip/project_blk_mem_gen_0_0/project_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/project/project_ooc.xdc
