# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/Nexys4_Master.xdc

# Block Designs: bd/exame/exame.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame || ORIG_REF_NAME==exame}]

# IP: bd/exame/ip/exame_blk_mem_gen_0_0/exame_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame_blk_mem_gen_0_0 || ORIG_REF_NAME==exame_blk_mem_gen_0_0}]

# IP: bd/exame/ip/exame_xlslice_0_0/exame_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame_xlslice_0_0 || ORIG_REF_NAME==exame_xlslice_0_0}]

# IP: bd/exame/ip/exame_xlslice_1_0/exame_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame_xlslice_1_0 || ORIG_REF_NAME==exame_xlslice_1_0}]

# IP: bd/exame/ip/exame_circuit_0_0/exame_circuit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame_circuit_0_0 || ORIG_REF_NAME==exame_circuit_0_0}]

# IP: bd/exame/ip/exame_EightDisplayControl_0_0/exame_EightDisplayControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame_EightDisplayControl_0_0 || ORIG_REF_NAME==exame_EightDisplayControl_0_0}]

# IP: bd/exame/ip/exame_xlslice_2_0/exame_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame_xlslice_2_0 || ORIG_REF_NAME==exame_xlslice_2_0}]

# IP: bd/exame/ip/exame_xlslice_2_1/exame_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exame_xlslice_2_1 || ORIG_REF_NAME==exame_xlslice_2_1}]

# XDC: bd/exame/ip/exame_blk_mem_gen_0_0/exame_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/exame/exame_ooc.xdc
