# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.cache/wt} [current_project]
set_property parent.project_path {/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /media/psf/Home/Development/ect_ua/UserRepository/Repository [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /media/psf/Home/Development/ect_ua/UserRepository/Memoria/4words4bits_3.coe
add_files {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.srcs/sources_1/bd/exame/exame.bd}}
set_property used_in_implementation false [get_files -all {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.srcs/sources_1/bd/exame/ip/exame_blk_mem_gen_0_0/exame_blk_mem_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.srcs/sources_1/bd/exame/exame_ooc.xdc}}]
set_property is_locked true [get_files {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.srcs/sources_1/bd/exame/exame.bd}}]

read_vhdl -library xil_defaultlib {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.srcs/sources_1/bd/exame/hdl/exame_wrapper.vhd}}
read_xdc {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.srcs/constrs_1/imports/xdc/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{/media/psf/Home/Development/ect_ua/UserRepository/Exames/P3 14 Abril 2015/project/project.srcs/constrs_1/imports/xdc/Nexys4_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top exame_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef exame_wrapper.dcp
catch { report_utilization -file exame_wrapper_utilization_synth.rpt -pb exame_wrapper_utilization_synth.pb }
