# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir I:/SDR_P/8/UserDefinedRepository/Unroll/Unroll.cache/wt [current_project]
set_property parent.project_path I:/SDR_P/8/UserDefinedRepository/Unroll/Unroll.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib I:/SDR_P/8/UserDefinedRepository/Unroll/Unroll.srcs/sources_1/new/TopUnroll.vhd
catch { write_hwdef -file TopUnr.hwdef }
synth_design -top TopUnr -part xc7a100tcsg324-1
write_checkpoint -noxdef TopUnr.dcp
catch { report_utilization -file TopUnr_utilization_synth.rpt -pb TopUnr_utilization_synth.pb }
