# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/Nexys4_Master.xdc

# Block Designs: bd/exam/exam.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam || ORIG_REF_NAME==exam}]

# IP: bd/exam/ip/exam_dist_mem_gen_0_0/exam_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_dist_mem_gen_0_0 || ORIG_REF_NAME==exam_dist_mem_gen_0_0}]

# IP: bd/exam/ip/exam_ROM_Reader1_0_0/exam_ROM_Reader1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_ROM_Reader1_0_0 || ORIG_REF_NAME==exam_ROM_Reader1_0_0}]

# IP: bd/exam/ip/exam_xlconcat_0_0/exam_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconcat_0_0 || ORIG_REF_NAME==exam_xlconcat_0_0}]

# IP: bd/exam/ip/exam_xlconstant_0_0/exam_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconstant_0_0 || ORIG_REF_NAME==exam_xlconstant_0_0}]

# IP: bd/exam/ip/exam_DC32_0_0/exam_DC32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_DC32_0_0 || ORIG_REF_NAME==exam_DC32_0_0}]

# IP: bd/exam/ip/exam_mux2p_0_0/exam_mux2p_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_mux2p_0_0 || ORIG_REF_NAME==exam_mux2p_0_0}]

# IP: bd/exam/ip/exam_circuit_c_0_0/exam_circuit_c_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_circuit_c_0_0 || ORIG_REF_NAME==exam_circuit_c_0_0}]

# IP: bd/exam/ip/exam_xlslice_0_0/exam_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlslice_0_0 || ORIG_REF_NAME==exam_xlslice_0_0}]

# IP: bd/exam/ip/exam_xlslice_1_0/exam_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlslice_1_0 || ORIG_REF_NAME==exam_xlslice_1_0}]

# IP: bd/exam/ip/exam_circuit_c_0_1/exam_circuit_c_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_circuit_c_0_1 || ORIG_REF_NAME==exam_circuit_c_0_1}]

# IP: bd/exam/ip/exam_xlconcat_1_0/exam_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconcat_1_0 || ORIG_REF_NAME==exam_xlconcat_1_0}]

# IP: bd/exam/ip/exam_xlslice_0_1/exam_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlslice_0_1 || ORIG_REF_NAME==exam_xlslice_0_1}]

# IP: bd/exam/ip/exam_xlslice_1_1/exam_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlslice_1_1 || ORIG_REF_NAME==exam_xlslice_1_1}]

# IP: bd/exam/ip/exam_xlconcat_1_1/exam_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconcat_1_1 || ORIG_REF_NAME==exam_xlconcat_1_1}]

# IP: bd/exam/ip/exam_circuit_c_0_2/exam_circuit_c_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_circuit_c_0_2 || ORIG_REF_NAME==exam_circuit_c_0_2}]

# IP: bd/exam/ip/exam_circuit_c_2_0/exam_circuit_c_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_circuit_c_2_0 || ORIG_REF_NAME==exam_circuit_c_2_0}]

# IP: bd/exam/ip/exam_circuito_m_0_0/exam_circuito_m_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_circuito_m_0_0 || ORIG_REF_NAME==exam_circuito_m_0_0}]

# IP: bd/exam/ip/exam_blk_mem_gen_0_0/exam_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_blk_mem_gen_0_0 || ORIG_REF_NAME==exam_blk_mem_gen_0_0}]

# IP: bd/exam/ip/exam_xlconstant_1_0/exam_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconstant_1_0 || ORIG_REF_NAME==exam_xlconstant_1_0}]

# IP: bd/exam/ip/exam_xlconstant_1_1/exam_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconstant_1_1 || ORIG_REF_NAME==exam_xlconstant_1_1}]

# IP: bd/exam/ip/exam_xlconstant_1_2/exam_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconstant_1_2 || ORIG_REF_NAME==exam_xlconstant_1_2}]

# IP: bd/exam/ip/exam_clock_divider_0_0/exam_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_clock_divider_0_0 || ORIG_REF_NAME==exam_clock_divider_0_0}]

# IP: bd/exam/ip/exam_showRam_0_0/exam_showRam_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_showRam_0_0 || ORIG_REF_NAME==exam_showRam_0_0}]

# IP: bd/exam/ip/exam_xlconcat_3_0/exam_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconcat_3_0 || ORIG_REF_NAME==exam_xlconcat_3_0}]

# IP: bd/exam/ip/exam_xlconstant_4_0/exam_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exam_xlconstant_4_0 || ORIG_REF_NAME==exam_xlconstant_4_0}]

# XDC: bd/exam/ip/exam_dist_mem_gen_0_0/exam_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/exam/ip/exam_blk_mem_gen_0_0/exam_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/exam/exam_ooc.xdc
